# application’s underlying servlet container listens for requests on this port
server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    # use import.sql to populate a schema created by Hibernate
    defer-datasource-initialization: true
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
  h2:
    console.enabled: true
  sql:
    init:
      mode: never