# application’s underlying servlet container listens for requests on this port
server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    # use import.sql to populate a schema created by Hibernate
    defer-datasource-initialization: true
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
  h2:
    console.enabled: true
  sql:
    init:
      mode: never
  security:
    oauth2:
      client:
        registration:
          facebook:
            # the 'clientID' and 'secret' are the credentials that identify application to Facebook
            clientId: <facebook client id>
            clientSecret: <facebook client secret>
            # specifies the access that the application will be granted
            scope: email, public_profile

# actuator
management:
  info:
    env:
      enabled: true
    # to get extremely detailed information about the Git commit
    git:
      enabled: true
      mode: full
  endpoints:
    web:
      base-path: /management
      exposure:
        include: '*'
        exclude: threaddump, heapdump
  endpoint:
    health:
      # to show the full details of all health indicators
      show-details: always

info:
  contact:
    email: gorshkovayulia93@gmail.com