# application’s underlying servlet container listens for requests on this port
server:
  port: 8090

spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
    schema: classpath:/sql/schema.sql
    data: classpath:/sql/data.sql
  jpa:
    # .sql files should not run before hibernate creates the tables
    defer-datasource-initialization: true
    generate-ddl: true
    properties:
      hibernate:
        # hibernate may not be detecting queries as MySQL queries (native queries)
        globally_quoted_identifiers: true
        # to avoid hibernate create the schema
        ddl-auto: none
        dialect: org.hibernate.dialect.HSQLDialect